### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [572006/prj-rev-bwfs-dasmoto#7]
https://github.com/572006/prj-rev-bwfs-dasmoto/blob/master/Art%20and%20Craft/style.css#L10-L32

There is a lot of repetition occurring in these rules and there are opportunities for refactoring. Try to extract the common styles into a single rule with a more general selector.

You've also missed the font-family style on several elements entirely. Consider using `*` to apply that style to all elements by default.

Example:

```css
* {
  font-family: Helvetica;
}

.product h2 {
  color: white;
  font-weight: bold;
  font-size: 32px;
}

#frames {
  background-color: lightcoral;
}
```
